name: 🐛 Bug Report
description: Report a bug in Genesis
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## Genesis Bug Report
        Help us fix issues in the Genesis AI system.

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of Genesis is affected?
      options:
        - Consciousness Matrix
        - Agent Nexus
        - Fusion Mode
        - Evolution Tree
        - UI Engine
        - Python Backend
        - Extension Modules
        - Build System
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Clear description of the bug
      placeholder: "When I try to..."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this?
      placeholder: |
        1. Open AgentNexus
        2. Select Aura persona
        3. Tap Fusion Mode
        4. Crash occurs
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happens?
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs/Stack Trace
      description: Paste any relevant logs or crash reports
      render: shell

  - type: input
    id: version
    attributes:
      label: Genesis Version
      placeholder: "v1.0.0"

  - type: input
    id: android
    attributes:
      label: Android Version
      placeholder: "Android 14"

  - type: input
    id: device
    attributes:
      label: Device
      placeholder: "Pixel 8 Pro"
