name: ✨ Feature Request
description: Suggest a new feature for Genesis
title: "[FEATURE] "
labels: [ "enhancement", "needs-review" ]
assignees: [ ]

body:
  - type: markdown
    attributes:
      value: |
        ## Genesis Feature Request
        Propose new capabilities for the Genesis AI system.

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Where should this feature be added?
      options:
        - Consciousness Matrix
        - Agent Nexus
        - Fusion Mode
        - Evolution Tree
        - UI Engine
        - Python Backend
        - Extension Modules
        - New Component
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: "As a Genesis user, I want to..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How should this feature work?
      placeholder: "The feature should..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other solutions did you consider?

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Examples
      description: Link to designs, screenshots, or similar features

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - Low - Nice to have
        - Medium - Would be useful
        - High - Important
        - Critical - Blocker
      default: 1
